apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: fit-forge
  labels:
    app: user-service
type: Opaque
stringData:
  MONGO_URI: "mongodb://user_user:pass@mongodb-0.mongodb-headless.fit-forge.svc.cluster.local:27017,mongodb-1.mongodb-headless.fit-forge.svc.cluster.local:27017,mongodb-2.mongodb-headless.fit-forge.svc.cluster.local:27017/user_db?replicaSet=rs0"
  JWT_SECRET: "alongtext"
