sonar.projectKey=fitforge-frontend
sonar.projectName=fitforge-frontend

# Source code location
sonar.sources=src

# Exclusions (VERY IMPORTANT for frontend)
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**

# Optional but good
sonar.sourceEncoding=UTF-8