apiVersion: v1
kind: Secret
metadata:
  name: nutrition-service-secret
  namespace: fit-forge
  labels:
    app: nutrition-service
type: Opaque
stringData:
  MONGO_URI: "mongodb://nutrition_user:password@mongodb-0.mongodb-headless.fit-forge.svc.cluster.local:27017,mongodb-1.mongodb-headless.fit-forge.svc.cluster.local:27017,mongodb-2.mongodb-headless.fit-forge.svc.cluster.local:27017/nutrition_db?replicaSet=rs0"
  JWT_SECRET: 
