apiVersion: v1
kind: Secret
metadata:
  name: workout-service-secret
  namespace: fit-forge
  labels:
    app: workout-service
type: Opaque
stringData:
  MONGO_URI: "mongodb://workout_user:9DRax5fzeA0SJYcz%2FdEOQk8bAsRyBkjh@mongodb-0.mongodb-headless.fit-forge.svc.cluster.local:27017,mongodb-1.mongodb-headless.fit-forge.svc.cluster.local:27017,mongodb-2.mongodb-headless.fit-forge.svc.cluster.local:27017/workout_db?replicaSet=rs0"
  JWT_SECRET: "4mZ_8xK2vW9uL_Qp5rN7yB3eT1hG6sJ9aC0dXzM_fVv"
