apiVersion: v1
kind: Secret
metadata:
  name: progress-service-secret
  namespace: fit-forge
  labels:
    app: progress-service
type: Opaque
stringData:
  MONGO_URI: "mongodb://progress_user:password@mongodb-0.mongodb-headless.fit-forge.svc.cluster.local:27017,mongodb-1.mongodb-headless.fit-forge.svc.cluster.local:27017,mongodb-2.mongodb-headless.fit-forge.svc.cluster.local:27017/progress_db?replicaSet=rs0"
  JWT_SECRET: "Alongtext"
