apiVersion: v1
kind: Secret
metadata:
  name: ai-agent-service-secret
  namespace: fit-forge
  labels:
    app: ai-agent-service
type: Opaque
stringData:
  MONGO_URI: "mongodb://nutrition_user:YZ2Hsqr8I0Kscxo0Y4pR1XZX7e437zSl@mongodb-0.mongodb-headless.fit-forge.svc.cluster.local:27017,mongodb-1.mongodb-headless.fit-forge.svc.cluster.local:27017,mongodb-2.mongodb-headless.fit-forge.svc.cluster.local:27017/nutrition_db?replicaSet=rs0"
  JWT_SECRET: "4mZ_8xK2vW9uL_Qp5rN7yB3eT1hG6sJ9aC0dXzM_fVv"
  GOOGLE_API_KEY: "AIzaSyDp6x4XyrydzexXfCgzfAXWWJvlS4uve9I"
  LLM_MODEL: "gemini-2.5-flash-lite"
