apiVersion: v1
kind: Secret
metadata:
  name: ai-agent-service-secret
  namespace: fit-forge
  labels:
    app: ai-agent-service
type: Opaque
stringData:
  MONGO_URI: 
  JWT_SECRET: 
  GOOGLE_API_KEY: 
  LLM_MODEL: "gemini-2.5-flash-lite"
