apiVersion: v1
kind: Service
metadata:
  name: ai-agent-service
  labels:
    app: ai-agent-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: ai-agent-service
