# Default values for user-service.

replicaCount: 1

image:
  repository: aswin018/k8s_mern_app_user-service
  pullPolicy: Always
  tag: "v3"

# Resources configured for Guaranteed QoS
resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

service:
  type: ClusterIP
  port: 5002
  targetPort: 5002

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 75
