name: CI Template

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      service-path:
        required: true
        type: string
      runtime:
        required: false
        type: string
        default: "node"
      node-version:
        required: false
        type: string
        default: "20"
      python-version:
        required: false
        type: string
        default: "3.11"
      environment:
        required: true
        type: string
    secrets:
      SNYK_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true
      SONAR_URL:
        required: true
      DOCKER_USERNAME_P:
        required: true
      DOCKER_PASSWORD_P:
        required: true

jobs:
  code-quality:
    name: "Code Quality - ${{ inputs.service-name }}"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    concurrency:
      group: code-quality-${{ inputs.service-name }}-${{ inputs.environment }}
      cancel-in-progress: false
    defaults:
      run:
        working-directory: ${{ inputs.service-path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        if: inputs.runtime == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: "${{ inputs.service-path }}/package-lock.json"

      - name: Setup Python
        if: inputs.runtime == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: "pip"

      - name: Install Node dependencies
        if: inputs.runtime == 'node'
        run: npm ci

      - name: Check unused dependencies(node)
        if: inputs.runtime == 'node'
        run: npx depcheck || true

      - name: Install Python dependencies
        if: inputs.runtime == 'python'
        run: pip install -r requirements.txt

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master

      - name: Install snyk-to-html
        run: npm install -g snyk-to-html

      - name: Snyk - Scan dependencies (Node)
        if: inputs.runtime == 'node'
        run: snyk test --severity-threshold=high --json-file-output=snyk-report.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Convert Snyk report to HTML(node)
        if: inputs.runtime == 'node'
        run: snyk-to-html -i snyk-report.json -o snyk-report.html

      - name: Snyk - Scan dependencies (Python)
        if: inputs.runtime == 'python'
        run: snyk test --file=requirements.txt --package-manager=pip --severity-threshold=high --json-file-output=snyk-report.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Convert Snyk report to HTML(python)
        if: inputs.runtime == 'python'
        run: snyk-to-html -i snyk-report.json -o snyk-report.html

      # SAST
      - name: Run Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: ${{ inputs.service-path }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}

      - name: Upload Snyk HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: snyk-report-${{ inputs.service-name }}
          path: ${{ inputs.service-path }}/snyk-report.html
          retention-days: 14

  build-publish:
    name: "Build & Publish - ${{ inputs.service-name }}"
    runs-on: ubuntu-latest
    needs: [code-quality]
    if: always() && needs.code-quality.result != 'failure' && needs.code-quality.result != 'cancelled'
    concurrency:
      group: build-publish-${{ inputs.service-name }}-${{ inputs.environment }}
      cancel-in-progress: false
    defaults:
      run:
        working-directory: ${{ inputs.service-path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Calculate Semantic Version (Main Only)
        id: semver
        if: inputs.environment == 'main'
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ github.token }}
          tag_prefix: ${{ inputs.service-name }}-v
          dry_run: true 
          default_bump: patch

      - name: Generate Tag
        id: tag
        run: |
          if [ "${{ inputs.environment }}" = "main" ]; then
            echo "tag=${{ steps.semver.outputs.new_tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=dev-${GITHUB_SHA}" >> $GITHUB_OUTPUT
          fi

      - name: Validate existing tag
        id: tag_check
        run: |
          TAG=${{ steps.tag.outputs.tag }}
          
          # Force fetch remote tags to ensure the local index knows about them
          git fetch --tags origin || true

          if git rev-parse "$TAG" >/dev/null 2>&1; then
            TAG_COMMIT=$(git rev-list -n 1 "$TAG")
            CURRENT_COMMIT=$(git rev-parse HEAD)

            if [ "$TAG_COMMIT" != "$CURRENT_COMMIT" ]; then
              echo "Tag exists but points to different commit!"
              exit 1
            fi

            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker
        run: |
          echo "${{ secrets.DOCKER_PASSWORD_P }}" | docker login -u "${{ secrets.DOCKER_USERNAME_P }}" --password-stdin

      - name: Check Docker image
        id: image_check
        run: |
          if docker manifest inspect ${{ secrets.DOCKER_USERNAME_P }}/${{ inputs.service-name }}:${{ steps.tag.outputs.tag }} > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker Image
        if: steps.image_check.outputs.exists != 'true'
        run: docker build -t ${{ secrets.DOCKER_USERNAME_P }}/${{ inputs.service-name }}:${{ steps.tag.outputs.tag }} .

      - name: Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        if: steps.image_check.outputs.exists != 'true'
        with: 
          image-ref: '${{ secrets.DOCKER_USERNAME_P }}/${{ inputs.service-name }}:${{ steps.tag.outputs.tag }}'
          format: 'table'
          output: 'trivy-report.txt'
          scan-type: 'image'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        if: always() && steps.image_check.outputs.exists != 'true'
        with:
          name: trivy-${{ inputs.service-name }}
          path: trivy-report.txt
          retention-days: 14

      - name: Push Docker Image
        if: steps.image_check.outputs.exists != 'true' && github.event_name != 'pull_request'
        run: docker push ${{ secrets.DOCKER_USERNAME_P }}/${{ inputs.service-name }}:${{ steps.tag.outputs.tag }}

      # CREATE TAG (ONLY IF NOT EXISTS)
      - name: Create Git Tag
        if: inputs.environment == 'main' && steps.tag_check.outputs.exists != 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git tag ${{ steps.tag.outputs.tag }}
          git push origin ${{ steps.tag.outputs.tag }}