name: CI Template

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      service-path:
        required: true
        type: string
      runtime:
        required: false
        type: string
        default: "node"
      node-version:
        required: false
        type: string
        default: "20"
      python-version:
        required: false
        type: string
        default: "3.11"
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  ci:
    name: "CI — ${{ inputs.service-name }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.service-path }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        if: inputs.runtime == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: "${{ inputs.service-path }}/package-lock.json"

      - name: Setup Python
        if: inputs.runtime == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: "pip"

      - name: Install Node dependencies
        if: inputs.runtime == 'node'
        run: npm ci

      - name: Check unused dependencies(node)
        if: inputs.runtime == 'node'
        run: npx depcheck || true

      - name: Install Python dependencies
        if: inputs.runtime == 'python'
        run: pip install -r requirements.txt

      # - name: Debug — Show current directory
      #   run: |
      #     echo "Current directory:"
      #     pwd

      # - name: Debug — List files
      #   run: |
      #     echo "Listing files:"
      #     ls -la

      # || true = report-only mode (won't fail the pipeline).
      # Remove || true when you're ready to enforce blocking on HIGH/CRITICAL.
      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master

      - name: Install snyk-to-html
        run: npm install -g snyk-to-html

      - name: Snyk — Scan dependencies (Node)
        if: inputs.runtime == 'node'
        run: snyk test --severity-threshold=high --json-file-output=snyk-report.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Convert Snyk report to HTML(node)
        if: inputs.runtime == 'node'
        run: snyk-to-html -i snyk-report.json -o snyk-report.html

      - name: Snyk — Scan dependencies (Python)
        if: inputs.runtime == 'python'
        run: snyk test --file=requirements.txt --package-manager=pip --severity-threshold=high --json-file-output=snyk-report.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Convert Snyk report to HTML(python)
        if: inputs.runtime == 'python'
        run: snyk-to-html -i snyk-report.json -o snyk-report.html

      # - name: Upload Snyk report
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: snyk-report-${{ inputs.service-name }}
      #     path: ${{ inputs.service-path }}/snyk-report.json
      #     retention-days: 14

      - name: Upload Snyk HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: snyk-report-${{ inputs.service-name }}
          path: |
            ${{ inputs.service-path }}/snyk-report-node.html
            ${{ inputs.service-path }}/snyk-report-python.html
          retention-days: 14
      
      SAST
      - name: Run Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: ${{ inputs.service-path }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://18.205.104.55:9000" 