name: CI - Nutrition Service

on:
  pull_request:
    branches: ["develop"]
  push:
    branches: ["feature/ci-nutrition-service"]
    paths:
      - "services/nutrition-service/**"


jobs:
  ci:
    uses: ./.github/workflows/_ci-template.yml
    with:
      service-name: nutrition-service
      service-path: ./services/nutrition-service
      runtime: node
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}