name: CI - Nutrition Service

on:
  pull_request:
    branches:
      - feature/ci-nutrition-service
  push:
    branches:
      - feature/ci-nutrition-service
    paths:
      - "services/nutrition-service/**"



jobs:
  ci:
    uses: ./.github/workflows/_ci-template.yml
    with:
      service-name: nutrition-service
      service-path: ./services/nutrition-service
      runtime: node
    secrets: inherit