name: CI — User Service

on:
  push:
    branches: 
      - features/trivy-arun
    paths:
      - "services/user-service/**"
      - ".github/workflows/ci-user-service.yml"
      - ".github/workflows/_ci-template.yml"
  pull_request:
    branches:
      - main-features
    paths:
      - "services/user-service/**"

jobs:
  ci:
    uses: ./.github/workflows/_ci-template.yml
    with:
      service-name: user-service
      service-path: services/user-service
      runtime: node
      node-version: "20"
    secrets: inherit
